import { Template, Plan, AppSettings, FeatureFlag } from './types';

export const seedPlans: Plan[] = [
  {
    id: 'plan-free',
    name: 'Free',
    description: 'Perfect for trying out PromoCard',
    price: 0,
    currency: 'USD',
    interval: 'monthly',
    features: [
      '5 cards per month',
      'Basic templates',
      'Standard export quality',
      'Watermark included',
      '1 saved brand kit',
    ],
    monthlyCardLimit: 5,
    brandKitsLimit: 1,
    exportQuality: 'low',
    watermarkEnabled: true,
    templateAccess: ['template-bio-basic', 'template-offer-basic'],
    prioritySupport: false,
    teamAccess: false,
    whiteLabel: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'plan-pro',
    name: 'Pro',
    description: 'For professionals and small businesses',
    price: 19,
    currency: 'USD',
    interval: 'monthly',
    features: [
      '50 cards per month',
      'All templates',
      'High export quality',
      'No watermark',
      '10 saved brand kits',
      'Priority support',
    ],
    monthlyCardLimit: 50,
    brandKitsLimit: 10,
    exportQuality: 'high',
    watermarkEnabled: false,
    templateAccess: ['*'],
    prioritySupport: true,
    teamAccess: false,
    whiteLabel: false,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'plan-business',
    name: 'Business',
    description: 'For growing teams and agencies',
    price: 49,
    currency: 'USD',
    interval: 'monthly',
    features: [
      'Unlimited cards',
      'All templates',
      'Premium export quality',
      'No watermark',
      'Unlimited brand kits',
      'Team access',
      'White-label option',
      'Priority support',
    ],
    monthlyCardLimit: -1,
    brandKitsLimit: -1,
    exportQuality: 'premium',
    watermarkEnabled: false,
    templateAccess: ['*'],
    prioritySupport: true,
    teamAccess: true,
    whiteLabel: true,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const seedTemplates: Template[] = [
  {
    id: 'template-bio-basic',
    name: 'Professional Bio Card',
    description: 'Clean and professional bio card for individuals',
    category: 'bio_card',
    niche: 'general',
    schema: {
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Full Name',
          placeholder: 'John Doe',
          required: true,
          maxLength: 50,
        },
        {
          id: 'title',
          type: 'text',
          label: 'Title/Role',
          placeholder: 'Software Engineer',
          required: true,
          maxLength: 50,
        },
        {
          id: 'description',
          type: 'textarea',
          label: 'About',
          placeholder: 'Brief description about yourself',
          required: true,
          maxLength: 200,
        },
        {
          id: 'phone',
          type: 'phone',
          label: 'Phone Number',
          placeholder: '+1 234 567 8900',
          required: false,
        },
        {
          id: 'email',
          type: 'text',
          label: 'Email',
          placeholder: 'john@example.com',
          required: false,
          validation: { pattern: '^[^@]+@[^@]+\\.[^@]+$' },
        },
        {
          id: 'website',
          type: 'url',
          label: 'Website',
          placeholder: 'https://yourwebsite.com',
          required: false,
        },
        {
          id: 'photo',
          type: 'image',
          label: 'Profile Photo',
          required: false,
        },
        {
          id: 'primaryColor',
          type: 'color',
          label: 'Primary Color',
          required: false,
          defaultValue: '#3B82F6',
        },
      ],
      layout: {
        type: 'vertical',
        sections: [
          {
            id: 'header',
            type: 'header',
            fields: ['photo', 'name', 'title'],
            style: {
              backgroundColor: '#ffffff',
              padding: '24px',
              borderRadius: '12px 12px 0 0',
            },
          },
          {
            id: 'body',
            type: 'body',
            fields: ['description'],
            style: {
              backgroundColor: '#ffffff',
              padding: '0 24px 24px',
            },
          },
          {
            id: 'footer',
            type: 'footer',
            fields: ['phone', 'email', 'website'],
            style: {
              backgroundColor: '#f8fafc',
              padding: '16px 24px',
              borderRadius: '0 0 12px 12px',
            },
          },
        ],
      },
      style: {
        fontFamily: 'Inter, sans-serif',
        baseFontSize: '16px',
        colors: {
          primary: '#3B82F6',
          secondary: '#64748B',
          accent: '#F59E0B',
          background: '#FFFFFF',
          text: '#1E293B',
        },
        spacing: {
          small: '8px',
          medium: '16px',
          large: '24px',
        },
      },
      exportPresets: [
        {
          id: 'story',
          name: 'Instagram Story',
          format: 'png',
          width: 1080,
          height: 1920,
          quality: 90,
        },
        {
          id: 'square',
          name: 'Square Post',
          format: 'png',
          width: 1080,
          height: 1080,
          quality: 90,
        },
      ],
    },
    isPremium: false,
    requiredPlan: [],
    isActive: true,
    order: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'template-clinic',
    name: 'Clinic Card',
    description: 'Professional card for medical clinics and healthcare',
    category: 'clinic_card',
    niche: 'healthcare',
    schema: {
      fields: [
        {
          id: 'clinicName',
          type: 'text',
          label: 'Clinic Name',
          placeholder: 'City Medical Clinic',
          required: true,
          maxLength: 60,
        },
        {
          id: 'doctorName',
          type: 'text',
          label: 'Doctor Name',
          placeholder: 'Dr. Sarah Johnson',
          required: true,
          maxLength: 50,
        },
        {
          id: 'specialty',
          type: 'text',
          label: 'Specialty',
          placeholder: 'Cardiologist',
          required: true,
          maxLength: 50,
        },
        {
          id: 'address',
          type: 'textarea',
          label: 'Address',
          placeholder: '123 Medical Center Dr',
          required: true,
          maxLength: 150,
        },
        {
          id: 'phone',
          type: 'phone',
          label: 'Phone',
          placeholder: '+1 234 567 8900',
          required: true,
        },
        {
          id: 'hours',
          type: 'text',
          label: 'Working Hours',
          placeholder: 'Mon-Fri: 9AM-6PM',
          required: false,
          maxLength: 50,
        },
        {
          id: 'logo',
          type: 'image',
          label: 'Clinic Logo',
          required: false,
        },
        {
          id: 'primaryColor',
          type: 'color',
          label: 'Primary Color',
          required: false,
          defaultValue: '#0EA5E9',
        },
      ],
      layout: {
        type: 'vertical',
        sections: [
          {
            id: 'header',
            type: 'header',
            fields: ['logo', 'clinicName'],
            style: {
              backgroundColor: '#0EA5E9',
              padding: '24px',
              borderRadius: '12px 12px 0 0',
            },
          },
          {
            id: 'body',
            type: 'body',
            fields: ['doctorName', 'specialty', 'address', 'phone', 'hours'],
            style: {
              backgroundColor: '#ffffff',
              padding: '24px',
            },
          },
        ],
      },
      style: {
        fontFamily: 'Inter, sans-serif',
        baseFontSize: '16px',
        colors: {
          primary: '#0EA5E9',
          secondary: '#64748B',
          accent: '#10B981',
          background: '#FFFFFF',
          text: '#1E293B',
        },
        spacing: {
          small: '8px',
          medium: '16px',
          large: '24px',
        },
      },
      exportPresets: [
        {
          id: 'story',
          name: 'Instagram Story',
          format: 'png',
          width: 1080,
          height: 1920,
          quality: 90,
        },
        {
          id: 'square',
          name: 'Square Post',
          format: 'png',
          width: 1080,
          height: 1080,
          quality: 90,
        },
      ],
    },
    isPremium: true,
    requiredPlan: ['plan-pro', 'plan-business'],
    isActive: true,
    order: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'template-offer-basic',
    name: 'Special Offer Card',
    description: 'Eye-catching card for promotions and offers',
    category: 'offer_card',
    niche: 'retail',
    schema: {
      fields: [
        {
          id: 'businessName',
          type: 'text',
          label: 'Business Name',
          placeholder: 'Your Business',
          required: true,
          maxLength: 50,
        },
        {
          id: 'offerTitle',
          type: 'text',
          label: 'Offer Title',
          placeholder: '50% OFF',
          required: true,
          maxLength: 40,
        },
        {
          id: 'offerDescription',
          type: 'textarea',
          label: 'Offer Details',
          placeholder: 'Describe your offer',
          required: true,
          maxLength: 150,
        },
        {
          id: 'validUntil',
          type: 'text',
          label: 'Valid Until',
          placeholder: 'Dec 31, 2024',
          required: false,
          maxLength: 30,
        },
        {
          id: 'cta',
          type: 'text',
          label: 'Call to Action',
          placeholder: 'Shop Now',
          required: true,
          maxLength: 20,
        },
        {
          id: 'logo',
          type: 'image',
          label: 'Logo',
          required: false,
        },
        {
          id: 'primaryColor',
          type: 'color',
          label: 'Primary Color',
          required: false,
          defaultValue: '#EF4444',
        },
      ],
      layout: {
        type: 'vertical',
        sections: [
          {
            id: 'header',
            type: 'header',
            fields: ['offerTitle', 'logo'],
            style: {
              backgroundColor: '#EF4444',
              padding: '32px',
              borderRadius: '12px 12px 0 0',
            },
          },
          {
            id: 'body',
            type: 'body',
            fields: ['businessName', 'offerDescription', 'validUntil'],
            style: {
              backgroundColor: '#ffffff',
              padding: '24px',
            },
          },
          {
            id: 'footer',
            type: 'footer',
            fields: ['cta'],
            style: {
              backgroundColor: '#FEF2F2',
              padding: '20px 24px',
              borderRadius: '0 0 12px 12px',
            },
          },
        ],
      },
      style: {
        fontFamily: 'Inter, sans-serif',
        baseFontSize: '16px',
        colors: {
          primary: '#EF4444',
          secondary: '#64748B',
          accent: '#F59E0B',
          background: '#FFFFFF',
          text: '#1E293B',
        },
        spacing: {
          small: '8px',
          medium: '16px',
          large: '24px',
        },
      },
      exportPresets: [
        {
          id: 'story',
          name: 'Instagram Story',
          format: 'png',
          width: 1080,
          height: 1920,
          quality: 90,
        },
        {
          id: 'square',
          name: 'Square Post',
          format: 'png',
          width: 1080,
          height: 1080,
          quality: 90,
        },
      ],
    },
    isPremium: false,
    requiredPlan: [],
    isActive: true,
    order: 3,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'template-tutor',
    name: 'Tutor Promo Card',
    description: 'Professional card for tutors and educators',
    category: 'tutor_card',
    niche: 'education',
    schema: {
      fields: [
        {
          id: 'name',
          type: 'text',
          label: 'Your Name',
          placeholder: 'Jane Smith',
          required: true,
          maxLength: 50,
        },
        {
          id: 'subjects',
          type: 'text',
          label: 'Subjects',
          placeholder: 'Math, Physics, Chemistry',
          required: true,
          maxLength: 100,
        },
        {
          id: 'experience',
          type: 'text',
          label: 'Experience',
          placeholder: '10+ years teaching',
          required: true,
          maxLength: 50,
        },
        {
          id: 'qualification',
          type: 'text',
          label: 'Qualification',
          placeholder: 'M.Sc. Physics',
          required: true,
          maxLength: 100,
        },
        {
          id: 'phone',
          type: 'phone',
          label: 'Phone',
          placeholder: '+1 234 567 8900',
          required: true,
        },
        {
          id: 'location',
          type: 'text',
          label: 'Location',
          placeholder: 'Online / City Center',
          required: false,
          maxLength: 50,
        },
        {
          id: 'photo',
          type: 'image',
          label: 'Your Photo',
          required: false,
        },
        {
          id: 'primaryColor',
          type: 'color',
          label: 'Primary Color',
          required: false,
          defaultValue: '#8B5CF6',
        },
      ],
      layout: {
        type: 'vertical',
        sections: [
          {
            id: 'header',
            type: 'header',
            fields: ['photo', 'name'],
            style: {
              backgroundColor: '#8B5CF6',
              padding: '24px',
              borderRadius: '12px 12px 0 0',
            },
          },
          {
            id: 'body',
            type: 'body',
            fields: ['subjects', 'experience', 'qualification', 'location'],
            style: {
              backgroundColor: '#ffffff',
              padding: '24px',
            },
          },
          {
            id: 'footer',
            type: 'footer',
            fields: ['phone'],
            style: {
              backgroundColor: '#F5F3FF',
              padding: '16px 24px',
              borderRadius: '0 0 12px 12px',
            },
          },
        ],
      },
      style: {
        fontFamily: 'Inter, sans-serif',
        baseFontSize: '16px',
        colors: {
          primary: '#8B5CF6',
          secondary: '#64748B',
          accent: '#F59E0B',
          background: '#FFFFFF',
          text: '#1E293B',
        },
        spacing: {
          small: '8px',
          medium: '16px',
          large: '24px',
        },
      },
      exportPresets: [
        {
          id: 'story',
          name: 'Instagram Story',
          format: 'png',
          width: 1080,
          height: 1920,
          quality: 90,
        },
        {
          id: 'square',
          name: 'Square Post',
          format: 'png',
          width: 1080,
          height: 1080,
          quality: 90,
        },
      ],
    },
    isPremium: true,
    requiredPlan: ['plan-pro', 'plan-business'],
    isActive: true,
    order: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'template-testimonial',
    name: 'Testimonial Card',
    description: 'Share customer testimonials beautifully',
    category: 'testimonial_card',
    niche: 'general',
    schema: {
      fields: [
        {
          id: 'customerName',
          type: 'text',
          label: 'Customer Name',
          placeholder: 'Alex Johnson',
          required: true,
          maxLength: 50,
        },
        {
          id: 'testimonial',
          type: 'textarea',
          label: 'Testimonial',
          placeholder: 'What customers say about you',
          required: true,
          maxLength: 200,
        },
        {
          id: 'businessName',
          type: 'text',
          label: 'Business Name',
          placeholder: 'Your Business',
          required: true,
          maxLength: 50,
        },
        {
          id: 'rating',
          type: 'select',
          label: 'Rating',
          required: true,
          options: ['5 stars', '4 stars', '3 stars'],
          defaultValue: '5 stars',
        },
        {
          id: 'logo',
          type: 'image',
          label: 'Business Logo',
          required: false,
        },
        {
          id: 'primaryColor',
          type: 'color',
          label: 'Primary Color',
          required: false,
          defaultValue: '#10B981',
        },
      ],
      layout: {
        type: 'vertical',
        sections: [
          {
            id: 'header',
            type: 'header',
            fields: ['logo', 'businessName'],
            style: {
              backgroundColor: '#10B981',
              padding: '24px',
              borderRadius: '12px 12px 0 0',
            },
          },
          {
            id: 'body',
            type: 'body',
            fields: ['testimonial', 'rating'],
            style: {
              backgroundColor: '#ffffff',
              padding: '24px',
            },
          },
          {
            id: 'footer',
            type: 'footer',
            fields: ['customerName'],
            style: {
              backgroundColor: '#ECFDF5',
              padding: '16px 24px',
              borderRadius: '0 0 12px 12px',
            },
          },
        ],
      },
      style: {
        fontFamily: 'Inter, sans-serif',
        baseFontSize: '16px',
        colors: {
          primary: '#10B981',
          secondary: '#64748B',
          accent: '#F59E0B',
          background: '#FFFFFF',
          text: '#1E293B',
        },
        spacing: {
          small: '8px',
          medium: '16px',
          large: '24px',
        },
      },
      exportPresets: [
        {
          id: 'story',
          name: 'Instagram Story',
          format: 'png',
          width: 1080,
          height: 1920,
          quality: 90,
        },
        {
          id: 'square',
          name: 'Square Post',
          format: 'png',
          width: 1080,
          height: 1080,
          quality: 90,
        },
      ],
    },
    isPremium: true,
    requiredPlan: ['plan-pro', 'plan-business'],
    isActive: true,
    order: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const seedAppSettings: AppSettings = {
  id: 'settings-default',
  appName: 'PromoCard',
  logo: '',
  brandColors: {
    primary: '#3B82F6',
    secondary: '#64748B',
    accent: '#F59E0B',
  },
  landingPage: {
    headline: 'Create Beautiful Shareable Cards in 60 Seconds',
    subheadline: 'Professional cards for social media, WhatsApp, and more. No design skills needed.',
    heroImage: '',
  },
  pricing: {
    freeMonthlyLimit: 5,
    freeExportQuality: 'low',
    paidExportQuality: 'high',
    watermarkText: 'Made with PromoCard',
    watermarkEnabled: true,
  },
  referral: {
    enabled: true,
    rewardType: 'free_exports',
    rewardValue: 5,
    expiryDays: 30,
  },
  announcements: {
    enabled: false,
    text: '',
    link: '',
    dismissible: true,
  },
  contact: {
    email: 'support@promocard.com',
    phone: '',
    supportUrl: '',
  },
  legal: {
    termsOfService: '',
    privacyPolicy: '',
  },
  updatedAt: new Date(),
};

export const seedFeatureFlags: FeatureFlag[] = [
  {
    id: 'flag-ai-captions',
    name: 'AI Captions',
    description: 'Enable AI-generated captions for cards',
    enabled: false,
    rolloutPercentage: 0,
    allowedPlans: ['plan-business'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'flag-team-accounts',
    name: 'Team Accounts',
    description: 'Enable team collaboration features',
    enabled: false,
    rolloutPercentage: 0,
    allowedPlans: ['plan-business'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'flag-api-access',
    name: 'API Access',
    description: 'Enable API access for developers',
    enabled: false,
    rolloutPercentage: 0,
    allowedPlans: ['plan-business'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
